apiVersion: 1

datasources:
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    # URL to remote Loki server
    # Replace LOKI_SERVER_HOST with your server's IP address or hostname
    url: http://LOKI_SERVER_HOST:3100
    isDefault: false
    editable: true
    jsonData:
      maxLines: 1000
      timeout: 60
      derivedFields:
        - datasourceUid: loki
          matcherRegex: "(?:traceID|trace_id)=(\\w+)"
          name: TraceID
          url: "$${__value.raw}"
