services:
  smtp-server:
    image: ghcr.io/lsflk/silver-smtp:main
    container_name: smtp-server-container
    ports:
      - "25:25"
      - "587:587"
    volumes:
      - ./silver-config/postfix/main.cf:/etc/postfix/main.cf:ro
      - ./silver-config/postfix/master.cf:/etc/postfix/master.cf:ro
      - ./silver-config/postfix/sqlite-virtual-domains.cf:/etc/postfix/sqlite-virtual-domains.cf:ro
      - ./silver-config/postfix/sqlite-virtual-users.cf:/etc/postfix/sqlite-virtual-users.cf:ro
      - ./silver-config/postfix/sqlite-virtual-aliases.cf:/etc/postfix/sqlite-virtual-aliases.cf:ro
      - ../conf/silver.yaml:/etc/postfix/silver.yaml
      - postfix-sasl:/var/spool/postfix/private
      - ./silver-config/certbot/keys/etc:/etc/letsencrypt:ro
      - ./silver-config/raven/data:/app/data:rw
      - raven-sockets:/var/run/raven # Shared socket directory
    networks:
      - mail-network
    depends_on:
      - opendkim-server
      - rspamd-server
      - certbot-server
      - raven-server

  raven-server:
    image: ghcr.io/lsflk/raven:latest
    container_name: raven
    ports:
      - "143:143"
      - "993:993"
      - "24:24"
    volumes:
      - ./silver-config/raven/conf:/etc/raven:rw
      - ./silver-config/raven/data:/app/data:rw
      - ./silver-config/raven/certs:/certs:ro
      - ./silver-config/raven/delivery.yaml:/etc/raven/delivery.yaml:ro
      - raven-sockets:/var/run/raven # Shared socket directory
      - postfix-sasl:/var/spool/postfix/private
    environment:
      - DB_FILE=/app/data/databases/shared.db
    networks:
      - mail-network
    restart: unless-stopped
    user: "0:0"

  opendkim-server:
    image: ghcr.io/lsflk/silver-dkim:main
    container_name: opendkim-server
    volumes:
      - ../conf/silver.yaml:/etc/opendkim/silver.yaml
      - ./silver-config/opendkim/opendkim.conf:/etc/opendkim/opendkim.conf:ro
      - ./silver-config/opendkim/KeyTable:/etc/opendkim/KeyTable:ro
      - ./silver-config/opendkim/SigningTable:/etc/opendkim/SigningTable:ro
      - ./silver-config/opendkim/TrustedHosts:/etc/opendkim/TrustedHosts:ro
      - dkim-keys:/etc/dkimkeys
    networks:
      - mail-network
    cap_drop:
      - all
    security_opt:
      - no-new-privileges:true

  rspamd-server:
    image: rspamd/rspamd:latest
    container_name: rspamd-server
    hostname: rspamd
    ports:
      - "11332:11332"
      - "11334:11334"
    volumes:
      - rspamd_data:/var/lib/rspamd
      - ./silver-config/rspamd/:/etc/rspamd/local.d:ro
      - clamsock:/var/run/clamav # shared socket volume
    networks:
      - mail-network

  clamav-server:
    image: clamav/clamav:latest # Official ClamAV image
    container_name: clamav-server
    volumes:
      - clamsock:/var/run/clamav
      - clamav_db:/var/lib/clamav
    networks:
      - mail-network
    restart: always
    depends_on:
      - rspamd-server
    environment:
      - CLAMAV_NO_FRESHCLAMD=false
    deploy:
      resources:
        limits:
          memory: 2.8G
        reservations:
          memory: 1G

  thunder-server:
    image: ghcr.io/asgardeo/thunder:latest
    container_name: thunder-server
    ports:
      - "127.0.0.1:8090:8090"
    networks:
      - mail-network
    volumes:
      - ./silver-config/thunder/certs/server.cert:/opt/thunder/repository/resources/security/server.cert:ro
      - ./silver-config/thunder/certs/server.key:/opt/thunder/repository/resources/security/server.key:ro
    depends_on:
      - certbot-server

  certbot-server:
    image: ghcr.io/lsflk/silver-certbot:main
    container_name: certbot-server
    volumes:
      - ./silver-config/certbot/keys/etc:/etc/letsencrypt
      - ./silver-config/certbot/keys/log:/var/log/letsencrypt
      - ./silver-config/certbot/keys/lib:/var/lib/letsencrypt"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - mail-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - type: bind
        source: ./silver-config/prometheus/prometheus.yml
        target: /etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    extra_hosts:
      - host.docker.internal=host-gateway
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"

volumes:
  postfix-sasl:
  dkim-keys:
  rspamd_data:
  clamsock:
  clamav_db:
  go-imap-data:
  raven-sockets:


networks:
  mail-network:
